#!/bin/bash
# MOAB/Torque submission script for multiple, dynamically-run 
# serial jobs on SciNet GPC
#
#PBS -l nodes=13:ppn=8,walltime=40:00:00
#PBS -N serialdynamicMulti
 
# DIRECTORY TO RUN - $PBS_O_WORKDIR is directory job was submitted from
cd $PBS_O_WORKDIR
 
# START PARALLEL JOBS USING NODE LIST IN $PBS_NODEFILE
seq 1 100 | parallel -j8 --sshloginfile $PBS_NODEFILE -W$PWD ./radio_job_caller added_sim_xcorr_nomean_rand {}
