"output_root" : "test",
"get_scalar_cls" : False,
"get_vector_cls" : False,
"get_tensor_cls" : False,
"get_transfer"   : True,
"do_lensing"     : False,
"do_nonlinear" : 0,
"l_max_scalar"      : 2000,
"k_eta_max_scalar"  : 4000,
"l_max_tensor"      : 1500,
"k_eta_max_tensor"  : 3000,
"use_physical"   : True,
"ombh2"          : 0.0226,
"omch2"          : 0.112,
"omnuh2"         : 0,
"omk"            : 0,
"hubble"         : 70,
"w"              : -1,
"cs2_lam"        : 1,
"temp_cmb"           : 2.725,
"helium_fraction"    : 0.24,
"massless_neutrinos" : 3.04,
"massive_neutrinos"  : 0,
"nu_mass_eigenstates" : 1,
"nu_mass_degeneracies" : 0,  
"nu_mass_fractions" : 1,
"initial_power_num"         : 1,
"pivot_scalar"              : 0.05,
"pivot_tensor"              : 0.05,
"scalar_amp(1)"             : 2.1e-9,
"scalar_spectral_index(1)"  : 0.96,
"scalar_nrun(1)"            : 0,
"tensor_spectral_index(1)"  : 0,
"initial_ratio(1)"          : 1,
"reionization"         : True,
"re_use_optical_depth" : True,
"re_optical_depth"     : 0.09,
"re_redshift"          : 11,
"re_delta_redshift"   : 1.5,
"re_ionization_frac"   : -1,
"RECFAST_fudge" : 1.14,
"RECFAST_fudge_He" : 0.86,
"RECFAST_Heswitch" : 6,
"RECFAST_Hswitch"  : True,
"initial_condition"   : 1,
"initial_vector" : "-1 0 0 0 0",
"vector_mode" : 0,
"COBE_normalize" : False,
"CMB_outputscale" : 7.4311e12,
"transfer_high_precision" : False,
"transfer_kmax"           : 2,
"transfer_k_per_logint"   : 0,
"transfer_num_redshifts"  : 1,
"transfer_interp_matterpower" : True,
"transfer_redshift(1)"    : 0,
"transfer_filename(1)"    : "Transfer_out.dat",
"transfer_matterpower(1)" : "matterpower.dat",
"scalar_output_file" : "scalCls.dat",
"vector_output_file" : "vecCls.dat",
"tensor_output_file" : "tensCls.dat",
"total_output_file"  : "totCls.dat",
"lensed_output_file" : "lensedCls.dat",
"lensed_total_output_file"  :"lensedtotCls.dat",
"lens_potential_output_file" : "lenspotentialCls.dat",
"FITS_filename"      : "scalCls.fits",
"do_lensing_bispectrum" : False,
"do_primordial_bispectrum" : False,
"bispectrum_nfields" : 2,
"bispectrum_slice_base_L" : 0,
"bispectrum_ndelta":3,
"bispectrum_delta(1)":0,
"bispectrum_delta(2)":2,
"bispectrum_delta(3)":4,
"bispectrum_do_fisher": False,
"bispectrum_fisher_noise":0,
"bispectrum_fisher_noise_pol":0,
"bispectrum_fisher_fwhm_arcmin":7,
"bispectrum_full_output_file":,
"feedback_level" : 1,
"lensing_method" : 1,
"accurate_BB": False,
"massive_nu_approx" : 3,
"accurate_polarization"   : True,
"accurate_reionization"   : True,
"do_tensor_neutrinos"     : False,
"do_late_rad_truncation"   : True,
"number_of_threads"       : 0,
"accuracy_boost"          : 1,
"l_accuracy_boost"        : 1,
"l_sample_boost"          : 1
