#!/bin/bash
while [ 1 ]
do
  #num=`ps aux | grep eswitzer | grep python | grep "R+" | wc -l`
  username=`whoami`
  num=`ls -1 /tmp | grep $username.busy | wc -l`
  stamp=`date +%s`
  #num=`ps aux | grep python | wc -l`
  echo $num
  if [ "$num" -lt "17" ]; then
    echo "< 17 running; spawning one more"
    #python pipeline/manager.py input/ers/crosspower/GBT_15hr_map_oldcal_cross_bulksim.ini >& bulksim$stamp.log &
    python pipeline/manager.py input/ers/crosspower/GBT_1hr_map_oldcal_cross_bulksim.ini >& bulksim$stamp.log &
  else
    echo ">= 17 running"
  fi
  sleep 2
done
