#!/bin/bash
for a in $(seq 0 99); do
    b=$(printf %03d ${a})
    echo $b
    sed -e "s/RANDINDEX/$b/g" wigglez_DR_correlate.template > wigglez_DR_correlate_rand$b.ini
    sed -e "s/RANDINDEX/$b/g" wigglez_DR_correlate_pbs.template > wigglez_DR_correlate_rand$b.pbs
    qsub wigglez_DR_correlate_rand$b.pbs
done
